name: Run Tests

inputs:
  nodeVersion:
    description: 'Node Version'
    required: false
    default: '16.x'
  npmToken:
    description: 'NPM Token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ inputs.nodeVersion }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'yarn'
    - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN -g
      env:
        NPM_TOKEN: ${{ inputs.npmToken }}
      shell: bash
    - run: |
        yarn
        yarn test --passWithNoTests
      shell: bash
